organization_lines:
  - Министерство науки и высшего образования Российской Федерации
  - Федеральное государственное автономное образовательное учреждение высшего образования
faculty: Институт прикладной математики и механики
department: Прикладная математика
work_type: ВЫПУСКНАЯ КВАЛИФИКАЦИОННАЯ РАБОТА
level: магистерская диссертация
title: >-
  Оценка шумового воздействия автомобильного транспорта с учётом региональной
  климатологии метеорологических условий распространения звука
author:  ________
group: ________
supervisor: ________
city: Санкт-Петербург
year: 2026
