"""
Step 5: Visualization.

Produces the figures that appear in the paper. Each function here generates
exactly one figure, saved to docs/figures/.

The figures are not exploratory — they are intended for publication. Defaults
should produce camera-ready output: correct font sizes for journal columns,
no axes-off chartjunk, colorblind-safe palettes, vector formats (PDF) for
line art and high-DPI raster (PNG, 300 dpi) for maps with continuous color.

────────────────────────────────────────────────────────────────────────────
Figure list (matches references in docs/article_draft.md)
────────────────────────────────────────────────────────────────────────────

polar_p_favorable_<cell>.pdf
    Polar plot of p_favorable vs. azimuth sector, with four curves:
    summer day, summer night, winter day, winter night. Plotted for one
    representative cell (e.g., city center near Pulkovo).
    This is the headline figure of the paper. The asymmetry visible here
    is the entire scientific narrative.

map_p_favorable_<sector>_<season>.pdf
    Spatial map of p_favorable across the SPb domain for one chosen
    (sector, season, period) combination. Shows whether climatology is
    spatially uniform or has structure (coastal effect, urban gradients).
    Multiple instances generated; e.g., NW sector × DJF × night and
    SE sector × JJA × day for contrast.

seasonal_cycle_p_favorable.pdf
    Annual cycle of p_favorable averaged over all sectors and cells, with
    separate curves for day/evening/night. Single panel, twelve-month axis.
    Useful in the introduction of Chapter 3 to show the seasonal envelope.

sector_season_heatmap.pdf
    Heatmap of p_favorable on (sector × season) axes, averaged across cells
    and periods. Compact summary of where and when in SPb conditions
    favor propagation. Good for the abstract figure or a paper teaser.

stability_agreement.pdf
    (Generated by Step 2.) Confusion matrix of Richardson vs. Pasquill
    classifications. Listed here for completeness.

buffer_comparison.pdf
    (NOT generated by this step — produced by downstream noise calculation
    code that consumes this project's lookup table. Listed for traceability.)

────────────────────────────────────────────────────────────────────────────
Visual conventions
────────────────────────────────────────────────────────────────────────────

- Probability axis: 0 to 1, with light gridlines at 0.25, 0.5, 0.75.
- Sample count threshold: estimates with n < 100 shown with reduced
  saturation or hatched, plus a footnote in the figure caption.
- Color palette: viridis for continuous, paired sequential for categorical
  comparisons (e.g., season × period gives 12 categories — use 4 hues × 3
  saturations).
- Font: Times-equivalent for compatibility with academic journal templates.
  Set via matplotlib rcParams in plotting_config().
- Polar plots: north up, clockwise (meteorological convention).

────────────────────────────────────────────────────────────────────────────
Implementation hints (for Claude Code)
────────────────────────────────────────────────────────────────────────────

Each plot function reads the lookup table once and plots from it. Don't
re-aggregate inside plot functions; if a plot needs differently aggregated
data, add an aggregation helper.

Cartopy is needed for the spatial maps. The SPb domain is small enough
that PlateCarree projection is fine; use coastlines() with high-res
('10m') because the Gulf of Finland coastline matters for context.

Polar plots: matplotlib's projection='polar' with theta_direction=-1
(clockwise) and theta_offset=π/2 (north up) is the conventional setup
for meteorological compass-rose-style plots.
"""

from pathlib import Path

import xarray as xr


def plotting_config() -> dict:
    """Return matplotlib rcParams for publication-quality figures."""
    raise NotImplementedError


def fig_polar_p_favorable(
    climatology: xr.Dataset, cell_index: int, output_path: Path
) -> None:
    """Headline polar plot for one cell, four season×period curves."""
    raise NotImplementedError


def fig_map_p_favorable(
    climatology: xr.Dataset,
    sector: int,
    season: str,
    period: str,
    output_path: Path,
) -> None:
    """Spatial map of p_favorable for one (sector, season, period) slice."""
    raise NotImplementedError


def fig_seasonal_cycle(climatology: xr.Dataset, output_path: Path) -> None:
    """Annual cycle of p_favorable averaged across cells and sectors."""
    raise NotImplementedError


def fig_sector_season_heatmap(climatology: xr.Dataset, output_path: Path) -> None:
    """Heatmap of p_favorable on sector × season axes."""
    raise NotImplementedError


def generate_all_figures(climatology: xr.Dataset, output_dir: Path) -> None:
    """Produce every figure in the paper figure list. Called by run.py viz."""
    raise NotImplementedError
